FROM tiangolo/meinheld-gunicorn-flask:python3.6-alpine3.8

ADD . .


RUN pip install --upgrade pip
RUN pip install -r ./requirements.txt
RUN pip install sqlalchemy_utils

#ENV GUNICORN_PATH ./gunicorn_conf.py
ENV MODULE_NAME "app"
ENV VARIABLE_NAME "app"

RUN flask db init
RUN flask db migrate -m "first migration"
RUN echo "'''${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

'''
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
${imports if imports else ''} 

# revision identifiers, used by Alembic.
revision = ${repr(up_revision)}
down_revision = ${repr(down_revision)}
branch_labels = ${repr(branch_labels)}
depends_on = ${repr(depends_on)}


def upgrade():
    ${upgrades if upgrades else 'pass'}


def downgrade():
    ${downgrades if downgrades else 'pass'}" > migrations/script.py.mako  



RUN flask db upgrade
