FROM tiangolo/meinheld-gunicorn-flask:python3.6-alpine3.8

ADD . .

#ENV GUNICORN_PATH ./gunicorn_conf.py
ENV MODULE_NAME "app"
ENV VARIABLE_NAME "app"

RUN flask db init
RUN flask db migrate -m "first migration"
RUN flask db upgrade

